app:
 name: springboot-config
 description: for learning config
my:
 greeting: spring-boot-config prod Hello world  from spring config server repo
 list:
  names: ajay,raghu,kumar 
db:
 connection: spring-boot-config prod connection-url
 host: spring-boot-config prod db_host
 port: 1234
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
